source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#

# if you have issues, likely because you have wrong ruby. need ruby < v3.2

# If you have any plugins, put them here!
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "github-pages", "~> 219", group: :jekyll_plugins
group :jekyll_plugins do
    gem 'jekyll-feed'
    gem 'jekyll-sitemap'
    gem 'jekyll-paginate'
    gem 'kramdown'
    # gem 'rouge'
    gem "webrick"
end
